version: '3.9'

services:
  db:
    image: postgres:15
    container_name: odoo_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:17
    container_name: odoo_app
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ./custom_addons:/mnt/extra-addons
      - odoo-web-data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: ["odoo", "-c", "/etc/odoo/odoo.conf"]

volumes:
  odoo-db-data:
  odoo-web-data:
